version: "3.8"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: VishuShah
      POSTGRES_PASSWORD: Vjune202001
      POSTGRES_DB: Grocerybase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # data persistence

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://VishuShah:Vjune202001@db:5432/Grocerybase"
    entrypoint: ["/app/wait-for-db.sh", "python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  volumes:
    postgres_data:  

  